name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 3.25.201.145
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/Epping-Table-Tennis-
            git pull
            cd server && npm install
            pm2 restart tt-api
            export $(grep -s DATABASE_URL ~/Epping-Table-Tennis-/server/.env) && psql $DATABASE_URL -c "UPDATE users SET password_hash='\$2a\$12\$KiPyX/BoOJM2u2JrXCtPheGwFqQHkl1YsLYfIf8Avp7.ST.cFtp/y' WHERE name ILIKE '%yankai%' RETURNING name;"
